M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu22.04.1} date 12.05.2025 (пн) 16:08:51
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-12T16:08:51+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.300
%
G90
G05
T1
X61.404Y5.329
X65.404Y5.329
T2
X26.289Y63.373
X37.719Y63.373
T3
X71.374Y71.374
T0
M30
